USE DATABASE WORKFORCE_INTELLIGENCE;
USE SCHEMA STAGE_WORKFORCE;

CREATE OR REPLACE TABLE EMPLOYEE_ACTUALS_STG AS
SELECT * FROM WORKFORCE_INTELLIGENCE.RAW_WORKFORCE.EMPLOYEE_ACTUALS_RAW WHERE 1=0;

CREATE OR REPLACE TABLE HEADCOUNT_PLAN_STG AS
SELECT * FROM WORKFORCE_INTELLIGENCE.RAW_WORKFORCE.HEADCOUNT_PLAN_RAW WHERE 1=0;

CREATE OR REPLACE TABLE HIRING_PLAN_STG AS
SELECT * FROM WORKFORCE_INTELLIGENCE.RAW_WORKFORCE.HIRING_PLAN_RAW WHERE 1=0;

CREATE OR REPLACE TABLE ATTRITION_PLAN_STG AS
SELECT * FROM WORKFORCE_INTELLIGENCE.RAW_WORKFORCE.ATTRITION_PLAN_RAW WHERE 1=0;

CREATE OR REPLACE TABLE ORG_DIMENSION_STG AS
SELECT * FROM WORKFORCE_INTELLIGENCE.RAW_WORKFORCE.ORG_DIMENSION_RAW WHERE 1=0;

CREATE OR REPLACE TABLE LOCATION_DIMENSION_STG AS
SELECT * FROM WORKFORCE_INTELLIGENCE.RAW_WORKFORCE.LOCATION_DIMENSION_RAW WHERE 1=0;