USE DATABASE WORKFORCE_INTELLIGENCE;
USE SCHEMA RAW_WORKFORCE;

CREATE OR REPLACE FILE FORMAT CSV_WORKFORCE_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE WORKFORCE_INBOUND_STAGE
    FILE_FORMAT = CSV_WORKFORCE_FORMAT;