USE DATABASE WORKFORCE_INTELLIGENCE;
USE SCHEMA RAW_WORKFORCE;

COPY INTO EMPLOYEE_ACTUALS_RAW
FROM @WORKFORCE_INBOUND_STAGE/employee_actuals.csv
FILE_FORMAT = (FORMAT_NAME = CSV_WORKFORCE_FORMAT)
ON_ERROR = CONTINUE;

COPY INTO HEADCOUNT_PLAN_RAW
FROM @WORKFORCE_INBOUND_STAGE/headcount_plan.csv
FILE_FORMAT = (FORMAT_NAME = CSV_WORKFORCE_FORMAT)
ON_ERROR = CONTINUE;

COPY INTO HIRING_PLAN_RAW
FROM @WORKFORCE_INBOUND_STAGE/hiring_plan.csv
FILE_FORMAT = (FORMAT_NAME = CSV_WORKFORCE_FORMAT)
ON_ERROR = CONTINUE;

COPY INTO ATTRITION_PLAN_RAW
FROM @WORKFORCE_INBOUND_STAGE/attrition_plan.csv
FILE_FORMAT = (FORMAT_NAME = CSV_WORKFORCE_FORMAT)
ON_ERROR = CONTINUE;

COPY INTO ORG_DIMENSION_RAW
FROM @WORKFORCE_INBOUND_STAGE/org_dimension.csv
FILE_FORMAT = (FORMAT_NAME = CSV_WORKFORCE_FORMAT)
ON_ERROR = CONTINUE;

COPY INTO LOCATION_DIMENSION_RAW
FROM @WORKFORCE_INBOUND_STAGE/location_dimension.csv
FILE_FORMAT = (FORMAT_NAME = CSV_WORKFORCE_FORMAT)
ON_ERROR = CONTINUE;